# Generated by Django 5.2.1 on 2025-05-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency_id',
            field=models.CharField(default='COP', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='mercado_pago_order_id',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_id',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_identification_number',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_identification_type',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_street_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_street_number',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_zip_code',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='CASH', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_detail',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='taxes_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('DEBIT_CARD', 'DEBIT_CARD'), ('CREDIT_CARD', 'CREDIT_CARD'), ('BANK_TRANSFER', 'BANK_TRANSFER'), ('NEQUI', 'NEQUI'), ('ACCOUNT_MONEY', 'ACCOUNT_MONEY'), ('OTHER', 'OTHER')], default='ACCOUNT_MONEY', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('IN_PROCESS', 'IN_PROCESS'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED'), ('REFUNDED', 'REFUNDED'), ('CHARGED_BACK', 'CHARGED_BACK')], default='PENDING', max_length=20),
        ),
    ]
