# Generated by Django 5.2.1 on 2025-05-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("shipments", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerinfo",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_info",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="customerinfo",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_info",
                to="shipments.shipment",
            ),
        ),
    ]
