# Generated by Django 5.2.1 on 2025-05-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofilesettings_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilesettings',
            name='public_key',
            field=models.CharField(default=' at 0x7aa636a81260>', editable=False, max_length=100),
        ),
    ]
