# Generated by Django 5.2.1 on 2025-05-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_remove_productreview_response_and_more"),
        ("users", "0008_alter_userprofilesettings_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilesettings",
            name="public_key",
            field=models.CharField(
                default=" at 0x70e129bd1260>", editable=False, max_length=100
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
