# Generated by Django 5.2.1 on 2025-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_rol_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
