# Generated by Django 5.2.1 on 2025-05-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_newslettersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilesettings",
            name="product_recommendation",
            field=models.BooleanField(default=False),
        ),
    ]
