# Generated by Django 5.2.1 on 2025-06-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_receive_monthly_newsletter_userprofilesettings_monthly_newsletter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
