# Generated by Django 5.2.1 on 2025-05-17 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customerinfo_order_alter_customerinfo_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wants_receive_notifications', models.BooleanField(default=True)),
                ('wants_receive_order_updates_notifications', models.BooleanField(default=True)),
                ('has_regard', models.BooleanField(default=False)),
                ('shares', models.IntegerField(default=0)),
                ('public_key', models.CharField(default=' at 0x78267e20c0>', editable=False, max_length=100)),
                ('referrals_who_was_purchased', models.IntegerField(default=0)),
                ('receive_monthly_newsletter', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
