# Generated by Django 5.2.1 on 2025-05-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofilesettings_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilesettings',
            name='public_key',
            field=models.CharField(default=' at 0x7f165760c0>', editable=False, max_length=100),
        ),
    ]
