# Generated by Django 5.2.1 on 2026-01-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0002_missingitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="additional_costs",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="total_purchase_price",
            field=models.FloatField(default=0),
        ),
    ]
