# Generated by Django 5.2.1 on 2026-01-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0003_purchase_additional_costs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="total_purchase_price",
        ),
    ]
