# Generated by Django 5.2.1 on 2025-05-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]
    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment_date_post_code',
            new_name='zip_code',
        ),
    ]
