# Generated by Django 5.2.1 on 2025-05-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('users', '0007_alter_userprofilesettings_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewresponse'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='responses',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_responses', to='users.comment'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='product_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.productreview'),
        ),
    ]
