# Generated by Django 5.2.1 on 2025-05-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_remove_productreview_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewresponse",
            name="user",
        ),
    ]
