# Generated by Django 5.2.1 on 2025-06-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_discount_applied_order_discount_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-creation_date"]},
        ),
    ]
