# Generated by Django 5.2.1 on 2025-05-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_order_user_remove_orderproduct_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missingitems",
            name="order",
        ),
        migrations.RemoveField(
            model_name="missingitems",
            name="product",
        ),
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.DeleteModel(
            name="MissingItems",
        ),
    ]
