# Generated by Django 5.2.1 on 2025-05-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_missingitems_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcart",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="productcart",
            name="measure_unity",
        ),
        migrations.RemoveField(
            model_name="productcart",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="ProductCart",
        ),
    ]
