# Generated by Django 5.2.1 on 2025-05-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productcart_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
