# Generated by Django 5.2.1 on 2025-05-21 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_delete_productreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="first_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_discount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="measure_unity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="product",
            name="second_image",
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.unitofmeasure",
                verbose_name="unit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
